export const SET_QUOTES = "QUOTES/SET_QUOTES";
export const GET_QUOTES_SUCCESS = "QUOTES/GET_QUOTES_SUCCESS";
export const GET_QUOTES_FAILED = "QUOTES/GET_QUOTES_FAILED";
export const GET_QUOTES_LOADING = "QUOTES/GET_QUOTES_LOADING";


export const SET_USER = "USER/SET_USER";
export const FETCH_LOADING_USER = "USER/FETCH_END_USER";
export const FETCH_SUCCESS_USER = "USER/FETCH_SUCCESS_USER";
export const FETCH_FAILURE_USER = "USER/FETCH_FAILURE_USER";

export const FETCH_START_USERS = "USER/FETCH_START_USERS";
export const FETCH_END_USERS = "USER/FETCH_END_USERS";
export const FETCH_FAILURE_USERS = "USER/FETCH_FAILURE_USERS";
export const FETCH_SUCCESS_USERS = "USER/FETCH_SUCCESS_USERS";
export const SET_USERS = "USERS/SET_USERS";


export const EXCHANGE_BOOK = "BOOKS/EXCHANGE_BOOK";
export const DELETE_BOOK = "BOOKS/DELETE-BOOK"
export const ADD_BOOK = "BOOKS/ADD_BOOK";
export const ADD_PROPOSAL = "BOOKS/ADD_PROPOSAL"
export const SET_BOOKS = "BOOKS/SET_BOOKS";
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const GET_BOOKS_LOADING = 'GET_BOOKS_LOADING';
export const GET_BOOKS_FAILED = 'GET_BOOKS_FAILED';
export const SET_BOOK = "BOOK/SET_BOOKS";
export const GET_BOOK_SUCCESS = "GET_BOOK_SUCCESS";
export const GET_BOOK_LOADING = "GET_BOOK_LOADING";
export const GET_BOOK_FAILED = "GET_BOOK_FAILED";


export const SET_SEARCH = 'SEARCH/SET_SEARCH';
export const LOGIN_SUCCESS = "AUTH/SUCCESS";
export const LOGIN_FAILURE = "AUTH/FAILURE";
export const LOGOUT = "AUTH/LOGOUT";

export const SET_LIKES = "LIKES/SET_LIKES";
export const GET_LIKES_SUCCESS = "LIKES/GET_LIKES_SUCCESS";
export const GET_LIKES_FAILED = "LIKES/GET_LIKES_FAILED";

export const SET_NOTICE = "NOTICE/SET_NOTICE";

export const GET_EXCHANGES_SUCCESS = "GET_EXCHANGES_SUCCESS";
export const GET_MY_EXCHANGES_SUCCESS = "GET_MY_EXCHANGES_SUCCESS";
export const GET_EXCHANGES_LOADING = "GET_EXCHANGES_LOADING";
export const GET_EXCHANGES_FAILED = "GET_EXCHANGES_FAILED";
export const DELETE_EXCHANGE = "DELETE_EXCHANGE"

